### PR TITLE
Bump cargo dependencies

### PR DESCRIPTION
**Pull request by mbestavros**
We'd like to enforce [`cargo-audit`](https://blog.rust-lang.org/inside-rust/2019/10/03/Keeping-secure-with-cargo-audit-0.9.html) testing on all new pull requests via Travis. PR #9 addresses this for `sevctl`, but the test currently fails due to out-of-date dependencies. This PR updates dependencies in `Cargo.lock` with `cargo update` to address this.

@steveeJ I cannot add reviewers myself on this repo; tagging you for review.

### CODE REVIEW

**Comment by mbestavros** [comment]
@steveeJ Yes, that's correct. I've reworded it to be a bit more specific.

**Comment by steveeJ** [comment]
> Yes, that's correct. I've reworded it to be a bit more specific.

Thanks. I think "Refresh Cargo lockfile with new dependencies" doesn't quite cut it either. Logically we're not introducing new dependencies. We're merely refreshing the lockfile to consider newer versions of the existing dependencies. From the cargo manpage: "Update dependencies as recorded in the local lock file.", so let's use "Cargo: update dependencies in lock file"?

**Comment by mbestavros** [comment]
Done.

**Comment by steveeJ** [comment]
As a last step, did you run `cargo test` on this after refreshing the lockfile?

**Comment by steveeJ** [comment]
> As a last step, did you run `cargo test` on this after refreshing the lockfile?

There aren't any tests defined yet, so that doesn't more than building the program, but at least it'll do that ;-)

**Comment by mbestavros** [comment]
@steveeJ Yes, compiles fine :smile:

**Comment by steveeJ** [comment]
> Yes, compiles fine smile

Thanks :wink:

**Pull request merged**
